# Generated by Django 6.0.1 on 2026-01-20 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(help_text='Kod kraju, Przykładowo: US, DE, FR, [...]', max_length=2)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LuggageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('design', models.CharField(help_text='Przykładowo: Boeing logo, call sign', max_length=100)),
                ('material', models.CharField(choices=[('PC', 'Plastik'), ('ML', 'Metal'), ('PH', 'Plusz'), ('LR', 'Skóra')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samoloty_sklep.category')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samoloty_sklep.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='AirplaneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aircraft_type', models.CharField(help_text='Przykładowo: Boeing 737, Airbus A320', max_length=100)),
                ('scale', models.CharField(choices=[('1:72', 'Skala 1:72'), ('1:144', 'Skala 1:144'), ('1:200', 'Skala 1:200'), ('1:400', 'Skala 1:400')], max_length=10)),
                ('material', models.CharField(choices=[('PC', 'Plastik'), ('ML', 'Metal'), ('PH', 'Plusz'), ('LR', 'Skóra')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samoloty_sklep.category')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samoloty_sklep.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='OtherGadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accessory_type', models.CharField(help_text='Przykładowo: plecak, torba, portfel', max_length=100)),
                ('material', models.CharField(choices=[('PC', 'Plastik'), ('ML', 'Metal'), ('PH', 'Plusz'), ('LR', 'Skóra')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samoloty_sklep.category')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samoloty_sklep.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='PlushToy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character', models.CharField(help_text='Przykładowo: samolot, pilot, stewardessa', max_length=100)),
                ('material', models.CharField(choices=[('PC', 'Plastik'), ('ML', 'Metal'), ('PH', 'Plusz'), ('LR', 'Skóra')], default='TX', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samoloty_sklep.category')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samoloty_sklep.manufacturer')),
            ],
        ),
    ]
