# Generated by Django 6.0.1 on 2026-01-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samoloty_sklep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clothing_type', models.CharField(choices=[('TE', 'T-shirt'), ('HE', 'Hoodie'), ('CP', 'Cap')], max_length=2)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('material', models.CharField(choices=[('PC', 'Plastik'), ('ML', 'Metal'), ('PH', 'Plusz'), ('LR', 'Skóra')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_ml', models.PositiveIntegerField()),
                ('material', models.CharField(choices=[('PC', 'Plastik'), ('ML', 'Metal'), ('PH', 'Plusz'), ('LR', 'Skóra')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='plushtoy',
            name='category',
        ),
        migrations.RemoveField(
            model_name='luggagetag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='airplanemodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='othergadget',
            name='category',
        ),
        migrations.AlterField(
            model_name='othergadget',
            name='manufacturer',
            field=models.CharField(choices=[('BO', 'Boeing'), ('AI', 'Airbus'), ('EM', 'Embraer'), ('CS', 'Cessna'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='luggagetag',
            name='manufacturer',
            field=models.CharField(choices=[('BO', 'Boeing'), ('AI', 'Airbus'), ('EM', 'Embraer'), ('CS', 'Cessna'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='plushtoy',
            name='manufacturer',
            field=models.CharField(choices=[('BO', 'Boeing'), ('AI', 'Airbus'), ('EM', 'Embraer'), ('CS', 'Cessna'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='airplanemodel',
            name='manufacturer',
            field=models.CharField(choices=[('BO', 'Boeing'), ('AI', 'Airbus'), ('EM', 'Embraer'), ('CS', 'Cessna'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='airplanemodel',
            name='aircraft_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='luggagetag',
            name='design',
            field=models.CharField(help_text='Przykładowo: BOEING LOGO, CALL SIGN', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
