# Generated by Django 6.0.1 on 2026-01-22 01:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samoloty_sklep', '0002_clothing_cup_remove_plushtoy_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=10)),
                ('airplane_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samoloty_sklep.airplanemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cup',
        ),
        migrations.DeleteModel(
            name='OtherGadget',
        ),
        migrations.AlterModelOptions(
            name='clothing',
            options={'verbose_name': 'Clothing', 'verbose_name_plural': 'Clothing'},
        ),
        migrations.AlterField(
            model_name='plushtoy',
            name='material',
            field=models.CharField(choices=[('PC', 'Plastik'), ('ML', 'Metal'), ('PH', 'Plusz'), ('LR', 'Skóra')], default='PH', max_length=2),
        ),
    ]
