# Generated by Django 6.0.1 on 2026-01-25 12:32

import samoloty_sklep.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samoloty_sklep', '0003_order_delete_cup_delete_othergadget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('CN', 'Cotton'), ('PR', 'Polyester'), ('AC', 'Acrylic'), ('WL', 'Wool')], max_length=2, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='airplanemodel',
            name='aircraft_type',
            field=models.CharField(max_length=100, validators=[samoloty_sklep.models.validate_capitalized]),
        ),
        migrations.AlterField(
            model_name='airplanemodel',
            name='manufacturer',
            field=models.CharField(choices=[('BO', 'Boeing'), ('AI', 'Airbus'), ('EM', 'Embraer'), ('CS', 'Cessna')], max_length=2),
        ),
        migrations.AlterField(
            model_name='airplanemodel',
            name='material',
            field=models.CharField(choices=[('PC', 'Plastic'), ('ML', 'Metal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='airplanemodel',
            name='name',
            field=models.CharField(max_length=100, validators=[samoloty_sklep.models.validate_capitalized]),
        ),
        migrations.AlterField(
            model_name='airplanemodel',
            name='scale',
            field=models.CharField(choices=[('1:72', 'Scale 1:72'), ('1:144', 'Scale 1:144'), ('1:200', 'Scale 1:200'), ('1:400', 'Scale 1:400')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='material',
        ),
        migrations.AlterField(
            model_name='clothing',
            name='name',
            field=models.CharField(max_length=100, validators=[samoloty_sklep.models.validate_capitalized]),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='luggagetag',
            name='material',
            field=models.CharField(choices=[('PC', 'Plastic'), ('ML', 'Metal'), ('PH', 'Plush'), ('LR', 'Leather')], max_length=2),
        ),
        migrations.AlterField(
            model_name='luggagetag',
            name='name',
            field=models.CharField(max_length=100, validators=[samoloty_sklep.models.validate_capitalized]),
        ),
        migrations.AlterField(
            model_name='plushtoy',
            name='character',
            field=models.CharField(help_text='Przykładowo: samolot, pilot, stewardessa', max_length=100, validators=[samoloty_sklep.models.validate_capitalized]),
        ),
        migrations.AlterField(
            model_name='plushtoy',
            name='material',
            field=models.CharField(choices=[('PC', 'Plastic'), ('ML', 'Metal'), ('PH', 'Plush'), ('LR', 'Leather')], default='PH', editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='plushtoy',
            name='name',
            field=models.CharField(max_length=100, validators=[samoloty_sklep.models.validate_capitalized]),
        ),
        migrations.AddField(
            model_name='clothing',
            name='material',
            field=models.ManyToManyField(blank=True, to='samoloty_sklep.clothingmaterial'),
        ),
    ]
